In [2]:
import numpy as np

# Basic Array Creation

In [7]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [9]:
a = [1,2,3,4,"hello"]
a

[1, 2, 3, 4, 'hello']

In [10]:
np.array(a)

array(['1', '2', '3', '4', 'hello'], dtype='<U11')

In [ ]:
# array me ek hi type ke  data type hote h (same data type only)
# agar alag alg hoge to vo use ek hi me convert kar dega jaise list a ko kiya h upar
# multi list ham create krte h lekin agar use aaray me convert karenge to vo one dimension me nhi  2 dimension me hoga 
#example given bellow

In [12]:
l = [[1,2,3],[4,5,6]]
l

[[1, 2, 3], [4, 5, 6]]

In [13]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6]])

# array generation function

In [15]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [18]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [19]:
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
arr = np.ones((3,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
arr = np.linspace(1,5,3)
arr

# starting,last, kitne element
# 1 and 5 ke bich 3 element with linear(equal) space

array([1., 3., 5.])

# Random generation function

In [24]:
np.random.rand(10)
# all values bw 0 and 1   ---- normalization

array([0.84249537, 0.62108994, 0.10006887, 0.77620892, 0.81775006,
       0.75519085, 0.8266217 , 0.96558123, 0.03565988, 0.59223275])

In [28]:
np.random.randn(10)
# all values bw -3 and 3 ----- Standardization

array([-1.60756519,  1.14238506, -0.26824732,  0.44654674, -0.53380788,
        0.99538354,  0.90279763, -0.67992399, -2.42519897, -0.87544237])

In [29]:
np.random.randint(6)

3

In [31]:
np.random.randint(10,20,4)

array([18, 15, 18, 18])

# Array Attributes

In [33]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr.shape

(3, 3)

In [35]:
arr.size

9

In [37]:
arr.dtype

dtype('int32')

# Array Methods

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr.min()

1

In [41]:
arr.max()

9

In [42]:
arr.sum()

45

In [43]:
np.sum(arr,axis = 0)
# for column wise sum 

array([12, 15, 18])

In [44]:
np.sum(arr, axis = 1)
# for row wise sum

array([ 6, 15, 24])

In [45]:
arr.mean()

5.0

In [46]:
arr.std()

2.581988897471611

In [47]:
arr.argmax()
# max index

8

In [48]:
arr.argmin()
# min index

0

# Reshaping and Resizing 

In [49]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [51]:
arr = arr.reshape(6,5)    # row,column
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

# Numpy Indexing and slicing of vectors

In [53]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [55]:
arr[6]

17

In [56]:
arr[1:5]

array([12, 13, 14, 15])

In [57]:
arr[:5]

array([11, 12, 13, 14, 15])

In [58]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [59]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [60]:
arr[1:5:2]
# starting , last+1 , steps

array([12, 14])

# Numpy Indexing and slicing of Matrix

In [61]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [62]:
arr[0]

array([1, 2, 3, 4, 5])

In [63]:
arr[5]
# row at index 5

array([26, 27, 28, 29, 30])

In [64]:
arr[0,0]

1

In [65]:
arr[2,3]

14

In [67]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [70]:
slice_1 = arr[3:,3:]
slice_1

array([[19, 20],
       [24, 25],
       [29, 30]])

In [72]:
arr[:,2]
# column at index 2

array([ 3,  8, 13, 18, 23, 28])

In [74]:
arr[:,4]

array([ 5, 10, 15, 20, 25, 30])

# Boolean index

In [75]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [76]:
boolean_index  = arr % 2 == 0
boolean_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [77]:
arr = arr[boolean_index]
arr

array([12, 14, 16, 18, 20])

# Array Operations

In [78]:
import numpy as np

Arithmetic Operation

In [79]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [80]:
a1 + a2
# must be the same size to perform operation

array([ 7,  9, 11, 13, 15])

In [81]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [83]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [85]:
a2 / a1

array([6.        , 3.5       , 2.66666667, 2.25      , 2.        ])

In [87]:
a2 // a1

array([6, 3, 2, 2, 2])

In [88]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

operation in matrix

In [92]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [93]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [94]:
arr2 * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

Broadcasting

In [90]:
l = np.array([10,20,30,40])
l

array([10, 20, 30, 40])

In [91]:
l + 10

array([20, 30, 40, 50])

Deep and Shallow copy

In [95]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [97]:
slice = a[:5]


array([1, 2, 3, 4, 5])

In [98]:
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [99]:
a
# after change in slice there is no change in original array
# sllice make own different space
# list me aisa nhi hota usme change ho jata h

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [100]:
a[4:6]

array([5, 6])

In [101]:
a[4:6] * 10

array([50, 60])

In [102]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [103]:
b = a

In [105]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [106]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [107]:
c = a.copy()
c
# copy karne par copy me change karne se original araay me koi change nhi hoga

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [108]:
c[1]=10
c

array([99, 10,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [109]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix operation

In [112]:
A = np.arange(1,5).reshape(2,2)
B = np.arange(5,9).reshape(2,2)

array([[5, 6],
       [7, 8]])

In [113]:
A @ B
# matrix  multiplication ke liye @ use karte h

array([[19, 22],
       [43, 50]])

In [114]:
 np.dot(A,B)
# matrix multiplication aise bhi kar skte h


array([[19, 22],
       [43, 50]])

In [115]:
A.T
# for Transpose

array([[1, 3],
       [2, 4]])

In [117]:
A

array([[1, 2],
       [3, 4]])

In [118]:
B

array([[5, 6],
       [7, 8]])

In [120]:
C = np.dot(A,B)
C

array([[19, 22],
       [43, 50]])

In [121]:
C.T

array([[19, 43],
       [22, 50]])

In [122]:
C

array([[19, 22],
       [43, 50]])

# Advance Array Manipulation

Stacking Array

In [123]:
# we can't stack two matrix vo lready hote h
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [125]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [126]:
np.hstack((a,b))
# ye 1 dimension me dega 

array([1, 2, 3, 4, 5, 6, 7, 8])

In [128]:
np.column_stack((a,b))
# agar 2D me chahiye to column_stack us karege 

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting Array

In [133]:
C = np.arange(16).reshape(4,4)
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [136]:
np.hsplit(C,2)
# kis matrix ko , kitne part me aur equal part me divide karta h 

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [137]:
np.vsplit(C,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
# splitting is also in 2D not in 1D

# Practice

In [152]:
# sudoku --- 9 rows with 3 by 3 devsion 
# sum of each row element is 45 ( each element in row are unique)
# sum of each column is 45   ( each element in column are unique)

s = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,8],
    [1,9,8,3,4,2,5,6,7],
    
    [8,5,9,7,6,1,4,2,3],
    [4,2,6,8,5,3,7,9,1],
    [7,1,3,9,2,4,8,5,6],

    [9,6,1,5,3,7,2,8,4],
    [2,8,7,4,1,9,6,3,5],
    [3,4,5,2,8,6,1,7,9]
])

In [153]:
b = np.sum(s,axis = 1)
b

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [158]:
for i in b:
    if i != 45:
        print("sudoku is not valid")
        break
    else:
        print("for rows it is valid")

for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid
for rows it is valid


In [159]:
d = np.sum(s,axis = 0)

In [160]:
for i in d:
    if i != 45:
        print("sudoku is not valid")
        break
    else:
        print("for column it is valid")

for column it is valid
for column it is valid
for column it is valid
for column it is valid
for column it is valid
for column it is valid
for column it is valid
for column it is valid
for column it is valid


In [161]:
s[:3,:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [164]:
s[:3,3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [165]:
s[:3,6:9]

array([[9, 1, 2],
       [3, 4, 8],
       [5, 6, 7]])

In [166]:
s[3:6,:3]

array([[8, 5, 9],
       [4, 2, 6],
       [7, 1, 3]])

In [167]:
s[3:6,3:6]

array([[7, 6, 1],
       [8, 5, 3],
       [9, 2, 4]])

In [168]:
s[3:6,6:9]

array([[4, 2, 3],
       [7, 9, 1],
       [8, 5, 6]])

In [169]:
s[6:9,:3]

array([[9, 6, 1],
       [2, 8, 7],
       [3, 4, 5]])

In [170]:
s[6:9,3:6]

array([[5, 3, 7],
       [4, 1, 9],
       [2, 8, 6]])

In [171]:
s[6:9,6:9]

array([[2, 8, 4],
       [6, 3, 5],
       [1, 7, 9]])

In [175]:
for i in range (0,9,3):
    for j in range (0,9,3):
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [206]:
import numpy as np
# columns : [age, math marks, science marks]

data = np.array([
    [18,85,78], # student 1
    [19,92,88], # student 2
    [17,76,95], # student 3
    [18,65,70], # student 4
    [20,90,85]  # student 5
])

In [207]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [208]:
#Find the average age of students.
np.mean(data[:,0:1])

18.4

In [209]:
#Extract Math marks of all students.

#for i in data:
  #  print(i[1])
    #or
data[:,1]

array([85, 92, 76, 65, 90])

In [210]:
#Find the highest Science mark.
np.max(data[:,2])

95

In [212]:
#Get details of the student who scored more than 90 in Math.
# mtlb unke age,math marks, science marks
data[data[:,1] > 90]

array([[19, 92, 88]])

In [213]:
#Increase Math marks of all students by 5.
data[:,1] += 5
data


array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [223]:
#Find how many students are younger than 19.
n = data[:,0] < 19
n.sum()
          #or 
 # len(data[data[:,0] < 19])

3

In [225]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:], axis = 0)

array([86.6, 83.2])

In [228]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [230]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])